const sb=window.supabase.createClient(OSOTUA_CONFIG.supabaseUrl,OSOTUA_CONFIG.supabaseKey);
const $=id=>document.getElementById(id);
let participants=[],participantMap=new Map(),currentDay=1;
let mediaRecorder=null,stream=null,chunks=[],audioBlob=null,timerId=null,seconds=0;

function log(m,e=false){$("log").textContent+=`\n[${new Date().toLocaleTimeString()}] ${e?"ERROR: ":""}${m}`;}
function setStatus(id,t,c=""){$(id).textContent=t;$(id).className=c;}
function network(){const on=navigator.onLine;$("networkBadge").textContent=on?"Online":"Offline";$("networkBadge").className=`badge ${on?"online":"offline"}`;}
function fmt(s){return `${String(Math.floor(s/60)).padStart(2,"0")}:${String(s%60).padStart(2,"0")}`;}

async function getSettings(){const{data,error}=await sb.from("project_settings").select("id,current_day").eq("id",1).single();if(error)throw error;currentDay=data.current_day;}
function renderToday(){const info=verseForDay(currentDay);$("dayTitle").textContent=`Day ${currentDay} · ${info.reference}`;$("verseText").textContent=info.text;$("adminCurrentDay").textContent=`Day ${currentDay}`;}
async function loadParticipants(){const{data,error}=await sb.from("participants").select("id,name,active").eq("active",true).order("name");if(error)throw error;participants=data;participantMap=new Map(data.map(x=>[x.id,x.name]));$("participantSelect").innerHTML='<option value="">Select your name</option>'+data.map(x=>`<option value="${x.id}">${x.name}</option>`).join("");}
async function initialize(){try{await getSettings();renderToday();await loadParticipants();const saved=localStorage.getItem("osotua_participant");if(saved&&participantMap.has(saved)){$("participantSelect").value=saved;await loadMyProgress();}await Promise.all([loadCommunity(),loadLeaderboard()]);}catch(e){log(e.message,true);}}

async function loadMyProgress(){const pid=$("participantSelect").value;if(!pid){$("myProgress").classList.add("hidden");return;}const{data,error}=await sb.from("memory_submissions").select("day").eq("participant_id",pid);if(error)throw error;const done=[...new Set(data.map(x=>x.day))],set=new Set(done),pct=Math.round(done.length/50*100);let streak=0;for(let d=currentDay;d>=1;d--){if(set.has(d))streak++;else break;}$("progressName").textContent=participantMap.get(pid);$("progressText").textContent=`${done.length} / 50`;$("progressFill").style.width=`${pct}%`;$("completedDays").textContent=done.length;$("progressPercent").textContent=`${pct}%`;$("streakCount").textContent=streak;$("dayGrid").innerHTML=Array.from({length:50},(_,i)=>i+1).map(d=>`<div class="day ${set.has(d)?"done":""} ${d===currentDay?"today":""}">${d}</div>`).join("");$("myProgress").classList.remove("hidden");}

async function diagnostics(){$("log").textContent="Starting diagnostics...";try{await loadParticipants();setStatus("apiStatus","Connected","pass");setStatus("participantsStatus",`${participants.length} loaded`,"pass");}catch(e){setStatus("apiStatus","Failed","fail");setStatus("participantsStatus","Failed","fail");log(e.message,true);}try{const{error}=await sb.storage.from(OSOTUA_CONFIG.bucket).list("",{limit:1});if(error)throw error;setStatus("storageStatus","Accessible","pass");}catch(e){setStatus("storageStatus","Failed","fail");log(e.message,true);}try{const{count,error}=await sb.from("memory_submissions").select("*",{count:"exact",head:true});if(error)throw error;setStatus("databaseStatus",`Accessible (${count||0})`,"pass");}catch(e){setStatus("databaseStatus","Failed","fail");log(e.message,true);}try{await getSettings();setStatus("settingsStatus",`Day ${currentDay}`,"pass");renderToday();}catch(e){setStatus("settingsStatus","Failed","fail");log(e.message,true);}}

async function startRecording(){try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];seconds=0;audioBlob=null;$("timer").textContent="00:00";mediaRecorder=new MediaRecorder(stream);mediaRecorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};mediaRecorder.onstop=()=>{audioBlob=new Blob(chunks,{type:mediaRecorder.mimeType||"audio/webm"});$("audioPreview").src=URL.createObjectURL(audioBlob);$("audioPreview").hidden=false;$("playRecording").disabled=false;$("submitRecording").disabled=false;$("submitStatus").textContent="Recording ready.";};mediaRecorder.start();timerId=setInterval(()=>{seconds++;$("timer").textContent=fmt(seconds);if(seconds>=180)stopRecording();},1000);$("startRecording").disabled=true;$("stopRecording").disabled=false;$("submitStatus").textContent="Recording…";}catch(e){$("submitStatus").textContent=e.message;log(e.message,true);}}
function stopRecording(){if(mediaRecorder&&mediaRecorder.state!=="inactive")mediaRecorder.stop();if(stream)stream.getTracks().forEach(t=>t.stop());clearInterval(timerId);$("startRecording").disabled=false;$("stopRecording").disabled=true;}

async function submitRecording(){const pid=$("participantSelect").value;if(!pid)return alert("Select your name.");if(!audioBlob)return alert("Record first.");const info=verseForDay(currentDay),name=participantMap.get(pid),path=`${name.replace(/[^a-zA-Z0-9_-]/g,"_")}/day-${currentDay}-${Date.now()}.webm`;try{$("submitStatus").textContent="Uploading…";const{error:u}=await sb.storage.from(OSOTUA_CONFIG.bucket).upload(path,audioBlob,{contentType:audioBlob.type||"audio/webm"});if(u)throw u;const{data:existing,error:q}=await sb.from("memory_submissions").select("id").eq("participant_id",pid).eq("day",currentDay).maybeSingle();if(q)throw q;let r;if(existing)r=await sb.from("memory_submissions").update({verse:info.verse,recording_path:path,submitted_at:new Date().toISOString()}).eq("id",existing.id);else r=await sb.from("memory_submissions").insert({participant_id:pid,day:currentDay,verse:info.verse,recording_path:path,submitted_at:new Date().toISOString()});if(r.error)throw r.error;$("submitStatus").textContent="✓ Submitted successfully";$("submitStatus").className="pass";await Promise.all([loadCommunity(),loadMyProgress(),loadLeaderboard()]);}catch(e){$("submitStatus").textContent=`Submit failed: ${e.message}`;$("submitStatus").className="fail";log(e.message,true);}}
async function signed(path){const{data,error}=await sb.storage.from(OSOTUA_CONFIG.bucket).createSignedUrl(path,3600);if(error)throw error;return data.signedUrl;}
async function loadCommunity(){if(!participants.length)await loadParticipants();const{data:rows,error}=await sb.from("memory_submissions").select("participant_id,recording_path,submitted_at").eq("day",currentDay);if(error)throw error;const m=new Map(rows.map(r=>[r.participant_id,r]));$("communitySummary").textContent=`${rows.length} / ${participants.length} submitted`;let html="";for(const p of participants){const r=m.get(p.id);if(!r){html+=`<div class="person-row"><span>${p.name}</span><strong>○ Not submitted</strong></div>`;continue;}let player;try{player=`<audio controls src="${await signed(r.recording_path)}"></audio>`;}catch{player='<span class="fail">Audio unavailable</span>';}html+=`<div class="person-row"><span><strong>${p.name}</strong><br><span class="pass">✓ Submitted</span><br><small>${new Date(r.submitted_at).toLocaleString()}</small></span>${player}</div>`;}$("communityList").innerHTML=html;}
async function loadLeaderboard(){const{data,error}=await sb.from("memory_submissions").select("participant_id,day");if(error)return;const counts=new Map();data.forEach(r=>counts.set(r.participant_id,(counts.get(r.participant_id)||new Set()).add(r.day)));const ranked=participants.map(p=>({name:p.name,count:counts.get(p.id)?.size||0})).sort((a,b)=>b.count-a.count||a.name.localeCompare(b.name));$("leaderboard").innerHTML=ranked.map((r,i)=>`<div class="rank-row"><span><strong>${i+1}. ${r.name}</strong></span><span>${r.count} / 50</span></div>`).join("");}

function openAdmin(){$("adminModal").classList.remove("hidden");}
function closeAdmin(){$("adminModal").classList.add("hidden");}
function adminLogin(){if($("adminPin").value!==OSOTUA_CONFIG.adminPin){$("adminLoginStatus").textContent="Incorrect PIN.";return;}$("adminLogin").classList.add("hidden");$("adminPanel").classList.remove("hidden");renderAdmin();}
async function renderAdmin(){$("adminCurrentDay").textContent=`Day ${currentDay}`;const{data,error}=await sb.from("participants").select("id,name,active").order("name");if(error)return;$("adminParticipants").innerHTML=data.map(p=>`<div class="admin-person"><span>${p.name} ${p.active?"":"(inactive)"}</span><button class="secondary" onclick="toggleParticipant('${p.id}',${!p.active})">${p.active?"Disable":"Enable"}</button></div>`).join("");const{count}=await sb.from("memory_submissions").select("*",{count:"exact",head:true}).eq("day",currentDay);$("adminStats").innerHTML=`<div><span>Submitted Today</span><strong>${count||0}</strong></div><div><span>Participants</span><strong>${data.filter(x=>x.active).length}</strong></div><div><span>Current Day</span><strong>${currentDay}</strong></div>`;}
async function saveDay(){const{error}=await sb.from("project_settings").update({current_day:currentDay,updated_at:new Date().toISOString()}).eq("id",1);$("daySaveStatus").textContent=error?error.message:"Saved.";if(!error){renderToday();await Promise.all([loadCommunity(),loadMyProgress(),loadLeaderboard()]);}}
async function addParticipant(){const name=$("newParticipantName").value.trim();if(!name)return;const{error}=await sb.from("participants").insert({name,active:true});$("participantAdminStatus").textContent=error?error.message:"Participant added.";$("newParticipantName").value="";await loadParticipants();await renderAdmin();await loadLeaderboard();}
window.toggleParticipant=async(id,active)=>{const{error}=await sb.from("participants").update({active}).eq("id",id);if(error)alert(error.message);await loadParticipants();await renderAdmin();await loadCommunity();await loadLeaderboard();};

$("participantSelect").onchange=()=>{localStorage.setItem("osotua_participant",$("participantSelect").value);loadMyProgress();};
$("startRecording").onclick=startRecording;$("stopRecording").onclick=stopRecording;$("playRecording").onclick=()=>$("audioPreview").play();$("submitRecording").onclick=submitRecording;$("refreshCommunity").onclick=loadCommunity;$("runDiagnostics").onclick=diagnostics;
$("openAdmin").onclick=openAdmin;$("closeAdmin").onclick=closeAdmin;$("adminLoginButton").onclick=adminLogin;
$("previousDay").onclick=()=>{currentDay=Math.max(1,currentDay-1);$("adminCurrentDay").textContent=`Day ${currentDay}`;};
$("nextDay").onclick=()=>{currentDay=Math.min(50,currentDay+1);$("adminCurrentDay").textContent=`Day ${currentDay}`;};
$("saveDay").onclick=saveDay;$("addParticipant").onclick=addParticipant;
window.addEventListener("online",network);window.addEventListener("offline",network);network();initialize();