const sb=window.supabase.createClient(OSOTUA_CONFIG.supabaseUrl,OSOTUA_CONFIG.supabaseKey);
const $=id=>document.getElementById(id);let recorder,stream,chunks=[],blob=null,peopleMap=new Map();
function log(m,e=false){$("log").textContent+=`\n[${new Date().toLocaleTimeString()}] ${e?"ERROR: ":""}${m}`;}
function stat(id,t,c=""){$(id).textContent=t;$(id).className=c;}
async function loadPeople(){const{data,error}=await sb.from("participants").select("id,name,active").eq("active",true).order("name");if(error)throw error;peopleMap=new Map(data.map(x=>[x.id,x.name]));$("participant").innerHTML='<option value="">Select your name</option>'+data.map(x=>`<option value="${x.id}">${x.name}</option>`).join("");return data;}
async function diagnostics(){stat("api","Testing…");try{const p=await loadPeople();stat("api","Connected","pass");stat("people",`${p.length} loaded`,"pass");log(`Participants loaded: ${p.length}`);}catch(e){stat("api","Failed","fail");stat("people","Failed","fail");log(e.message,true);}
try{const{data,error}=await sb.storage.from(OSOTUA_CONFIG.bucket).list("",{limit:5});if(error)throw error;stat("storage","Accessible","pass");log(`Storage accessible: ${data.length} item(s)`);}catch(e){stat("storage","Failed","fail");log(e.message,true);}
try{const{count,error}=await sb.from("memory_submissions").select("*",{count:"exact",head:true});if(error)throw error;stat("db",`Accessible (${count||0})`,"pass");log(`Database accessible: ${count||0} row(s)`);}catch(e){stat("db","Failed","fail");log(e.message,true);}}
$("start").onclick=async()=>{try{stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks=[];recorder=new MediaRecorder(stream);recorder.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};recorder.onstop=()=>{blob=new Blob(chunks,{type:recorder.mimeType||"audio/webm"});$("preview").src=URL.createObjectURL(blob);$("preview").hidden=false;$("play").disabled=false;$("submit").disabled=false;$("submitStatus").textContent=`Recording ready (${Math.ceil(blob.size/1024)} KB)`;log("Recording ready");};recorder.start();$("start").disabled=true;$("stop").disabled=false;$("submitStatus").textContent="Recording…";log("Recording started");}catch(e){$("submitStatus").textContent=e.message;log(e.message,true);}};
$("stop").onclick=()=>{if(recorder&&recorder.state!=="inactive")recorder.stop();if(stream)stream.getTracks().forEach(t=>t.stop());$("start").disabled=false;$("stop").disabled=true;};
$("play").onclick=()=>$("preview").play();
$("submit").onclick=async()=>{const pid=$("participant").value;if(!pid)return alert("Select your name.");if(!blob)return alert("Record first.");const name=peopleMap.get(pid)||"participant";const path=`${name.replace(/[^a-zA-Z0-9_-]/g,"_")}/day-1-${Date.now()}.webm`;try{$("submitStatus").textContent="Uploading audio…";const{error:uerr}=await sb.storage.from(OSOTUA_CONFIG.bucket).upload(path,blob,{contentType:blob.type||"audio/webm"});if(uerr)throw uerr;log("Audio uploaded");$("submitStatus").textContent="Saving submission…";const{error:derr}=await sb.from("memory_submissions").upsert({participant_id:pid,day:1,verse:1,recording_path:path,submitted_at:new Date().toISOString()},{onConflict:"participant_id,day"});if(derr)throw derr;$("submitStatus").textContent="✓ Submitted successfully";$("submitStatus").className="pass";log("Submission saved");loadCommunity();}catch(e){$("submitStatus").textContent=`Submit failed: ${e.message}`;$("submitStatus").className="fail";log(e.message,true);}};
async function loadCommunity(){try{const p=await loadPeople();const{data:rows,error}=await sb.from("memory_submissions").select("participant_id,recording_path").eq("day",1);if(error)throw error;const m=new Map(rows.map(r=>[r.participant_id,r]));$("summary").textContent=`${rows.length} / ${p.length} submitted`;let html="";for(const person of p){const r=m.get(person.id);if(!r){html+=`<div class="person">${person.name} — Not submitted</div>`;continue;}const{sdata,error:sErr}=await (async()=>{const x=await sb.storage.from(OSOTUA_CONFIG.bucket).createSignedUrl(r.recording_path,3600);return{sdata:x.data,error:x.error}})();html+=sErr?`<div class="person">${person.name} — Submitted (audio unavailable)</div>`:`<div class="person"><b>${person.name}</b> ✓<audio controls src="${sdata.signedUrl}"></audio></div>`;}$("community").innerHTML=html;}catch(e){$("summary").textContent=e.message;log(e.message,true);}}
$("run").onclick=diagnostics;$("refresh").onclick=loadCommunity;loadPeople().catch(e=>log(e.message,true));loadCommunity();